---
- name: Pull docker image of Calculator
  hosts: all
  tasks:
    - name: Start docker service
      service:
        name: docker
        state: started

    - name: pull docker image
      shell: docker pull saurabhdocker001/speminiproject:latest

    - name: running container
      shell: docker run -it -d saurabhdocker001/speminiproject:latest /bin/bash
